services:
  reval:
    build: 
      context: .
      dockerfile: build/reval/Dockerfile
      
    image: local/reval:latest
    ports:
      - "8080:8080"
    volumes:
      - "./tmp/:/app/data/" #sqlite database path