// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rherlt/reval/ent/evaluation"
	"github.com/rherlt/reval/ent/evaluationprompt"
	"github.com/rherlt/reval/ent/predicate"
)

// EvaluationPromptQuery is the builder for querying EvaluationPrompt entities.
type EvaluationPromptQuery struct {
	config
	ctx             *QueryContext
	order           []evaluationprompt.OrderOption
	inters          []Interceptor
	predicates      []predicate.EvaluationPrompt
	withEvaluations *EvaluationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EvaluationPromptQuery builder.
func (epq *EvaluationPromptQuery) Where(ps ...predicate.EvaluationPrompt) *EvaluationPromptQuery {
	epq.predicates = append(epq.predicates, ps...)
	return epq
}

// Limit the number of records to be returned by this query.
func (epq *EvaluationPromptQuery) Limit(limit int) *EvaluationPromptQuery {
	epq.ctx.Limit = &limit
	return epq
}

// Offset to start from.
func (epq *EvaluationPromptQuery) Offset(offset int) *EvaluationPromptQuery {
	epq.ctx.Offset = &offset
	return epq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (epq *EvaluationPromptQuery) Unique(unique bool) *EvaluationPromptQuery {
	epq.ctx.Unique = &unique
	return epq
}

// Order specifies how the records should be ordered.
func (epq *EvaluationPromptQuery) Order(o ...evaluationprompt.OrderOption) *EvaluationPromptQuery {
	epq.order = append(epq.order, o...)
	return epq
}

// QueryEvaluations chains the current query on the "evaluations" edge.
func (epq *EvaluationPromptQuery) QueryEvaluations() *EvaluationQuery {
	query := (&EvaluationClient{config: epq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := epq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := epq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationprompt.Table, evaluationprompt.FieldID, selector),
			sqlgraph.To(evaluation.Table, evaluation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evaluationprompt.EvaluationsTable, evaluationprompt.EvaluationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(epq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EvaluationPrompt entity from the query.
// Returns a *NotFoundError when no EvaluationPrompt was found.
func (epq *EvaluationPromptQuery) First(ctx context.Context) (*EvaluationPrompt, error) {
	nodes, err := epq.Limit(1).All(setContextOp(ctx, epq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{evaluationprompt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (epq *EvaluationPromptQuery) FirstX(ctx context.Context) *EvaluationPrompt {
	node, err := epq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EvaluationPrompt ID from the query.
// Returns a *NotFoundError when no EvaluationPrompt ID was found.
func (epq *EvaluationPromptQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = epq.Limit(1).IDs(setContextOp(ctx, epq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{evaluationprompt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (epq *EvaluationPromptQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := epq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EvaluationPrompt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EvaluationPrompt entity is found.
// Returns a *NotFoundError when no EvaluationPrompt entities are found.
func (epq *EvaluationPromptQuery) Only(ctx context.Context) (*EvaluationPrompt, error) {
	nodes, err := epq.Limit(2).All(setContextOp(ctx, epq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{evaluationprompt.Label}
	default:
		return nil, &NotSingularError{evaluationprompt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (epq *EvaluationPromptQuery) OnlyX(ctx context.Context) *EvaluationPrompt {
	node, err := epq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EvaluationPrompt ID in the query.
// Returns a *NotSingularError when more than one EvaluationPrompt ID is found.
// Returns a *NotFoundError when no entities are found.
func (epq *EvaluationPromptQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = epq.Limit(2).IDs(setContextOp(ctx, epq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{evaluationprompt.Label}
	default:
		err = &NotSingularError{evaluationprompt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (epq *EvaluationPromptQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := epq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EvaluationPrompts.
func (epq *EvaluationPromptQuery) All(ctx context.Context) ([]*EvaluationPrompt, error) {
	ctx = setContextOp(ctx, epq.ctx, "All")
	if err := epq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EvaluationPrompt, *EvaluationPromptQuery]()
	return withInterceptors[[]*EvaluationPrompt](ctx, epq, qr, epq.inters)
}

// AllX is like All, but panics if an error occurs.
func (epq *EvaluationPromptQuery) AllX(ctx context.Context) []*EvaluationPrompt {
	nodes, err := epq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EvaluationPrompt IDs.
func (epq *EvaluationPromptQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if epq.ctx.Unique == nil && epq.path != nil {
		epq.Unique(true)
	}
	ctx = setContextOp(ctx, epq.ctx, "IDs")
	if err = epq.Select(evaluationprompt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (epq *EvaluationPromptQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := epq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (epq *EvaluationPromptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, epq.ctx, "Count")
	if err := epq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, epq, querierCount[*EvaluationPromptQuery](), epq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (epq *EvaluationPromptQuery) CountX(ctx context.Context) int {
	count, err := epq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (epq *EvaluationPromptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, epq.ctx, "Exist")
	switch _, err := epq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (epq *EvaluationPromptQuery) ExistX(ctx context.Context) bool {
	exist, err := epq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EvaluationPromptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (epq *EvaluationPromptQuery) Clone() *EvaluationPromptQuery {
	if epq == nil {
		return nil
	}
	return &EvaluationPromptQuery{
		config:          epq.config,
		ctx:             epq.ctx.Clone(),
		order:           append([]evaluationprompt.OrderOption{}, epq.order...),
		inters:          append([]Interceptor{}, epq.inters...),
		predicates:      append([]predicate.EvaluationPrompt{}, epq.predicates...),
		withEvaluations: epq.withEvaluations.Clone(),
		// clone intermediate query.
		sql:  epq.sql.Clone(),
		path: epq.path,
	}
}

// WithEvaluations tells the query-builder to eager-load the nodes that are connected to
// the "evaluations" edge. The optional arguments are used to configure the query builder of the edge.
func (epq *EvaluationPromptQuery) WithEvaluations(opts ...func(*EvaluationQuery)) *EvaluationPromptQuery {
	query := (&EvaluationClient{config: epq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	epq.withEvaluations = query
	return epq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Prompt string `json:"prompt,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EvaluationPrompt.Query().
//		GroupBy(evaluationprompt.FieldPrompt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (epq *EvaluationPromptQuery) GroupBy(field string, fields ...string) *EvaluationPromptGroupBy {
	epq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EvaluationPromptGroupBy{build: epq}
	grbuild.flds = &epq.ctx.Fields
	grbuild.label = evaluationprompt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Prompt string `json:"prompt,omitempty"`
//	}
//
//	client.EvaluationPrompt.Query().
//		Select(evaluationprompt.FieldPrompt).
//		Scan(ctx, &v)
func (epq *EvaluationPromptQuery) Select(fields ...string) *EvaluationPromptSelect {
	epq.ctx.Fields = append(epq.ctx.Fields, fields...)
	sbuild := &EvaluationPromptSelect{EvaluationPromptQuery: epq}
	sbuild.label = evaluationprompt.Label
	sbuild.flds, sbuild.scan = &epq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EvaluationPromptSelect configured with the given aggregations.
func (epq *EvaluationPromptQuery) Aggregate(fns ...AggregateFunc) *EvaluationPromptSelect {
	return epq.Select().Aggregate(fns...)
}

func (epq *EvaluationPromptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range epq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, epq); err != nil {
				return err
			}
		}
	}
	for _, f := range epq.ctx.Fields {
		if !evaluationprompt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if epq.path != nil {
		prev, err := epq.path(ctx)
		if err != nil {
			return err
		}
		epq.sql = prev
	}
	return nil
}

func (epq *EvaluationPromptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EvaluationPrompt, error) {
	var (
		nodes       = []*EvaluationPrompt{}
		_spec       = epq.querySpec()
		loadedTypes = [1]bool{
			epq.withEvaluations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EvaluationPrompt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EvaluationPrompt{config: epq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, epq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := epq.withEvaluations; query != nil {
		if err := epq.loadEvaluations(ctx, query, nodes,
			func(n *EvaluationPrompt) { n.Edges.Evaluations = []*Evaluation{} },
			func(n *EvaluationPrompt, e *Evaluation) { n.Edges.Evaluations = append(n.Edges.Evaluations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (epq *EvaluationPromptQuery) loadEvaluations(ctx context.Context, query *EvaluationQuery, nodes []*EvaluationPrompt, init func(*EvaluationPrompt), assign func(*EvaluationPrompt, *Evaluation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*EvaluationPrompt)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(evaluation.FieldEvaluationPromptId)
	}
	query.Where(predicate.Evaluation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evaluationprompt.EvaluationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.EvaluationPromptId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "evaluationPromptId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (epq *EvaluationPromptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := epq.querySpec()
	_spec.Node.Columns = epq.ctx.Fields
	if len(epq.ctx.Fields) > 0 {
		_spec.Unique = epq.ctx.Unique != nil && *epq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, epq.driver, _spec)
}

func (epq *EvaluationPromptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(evaluationprompt.Table, evaluationprompt.Columns, sqlgraph.NewFieldSpec(evaluationprompt.FieldID, field.TypeUUID))
	_spec.From = epq.sql
	if unique := epq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if epq.path != nil {
		_spec.Unique = true
	}
	if fields := epq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationprompt.FieldID)
		for i := range fields {
			if fields[i] != evaluationprompt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := epq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := epq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := epq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := epq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (epq *EvaluationPromptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(epq.driver.Dialect())
	t1 := builder.Table(evaluationprompt.Table)
	columns := epq.ctx.Fields
	if len(columns) == 0 {
		columns = evaluationprompt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if epq.sql != nil {
		selector = epq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if epq.ctx.Unique != nil && *epq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range epq.predicates {
		p(selector)
	}
	for _, p := range epq.order {
		p(selector)
	}
	if offset := epq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := epq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EvaluationPromptGroupBy is the group-by builder for EvaluationPrompt entities.
type EvaluationPromptGroupBy struct {
	selector
	build *EvaluationPromptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (epgb *EvaluationPromptGroupBy) Aggregate(fns ...AggregateFunc) *EvaluationPromptGroupBy {
	epgb.fns = append(epgb.fns, fns...)
	return epgb
}

// Scan applies the selector query and scans the result into the given value.
func (epgb *EvaluationPromptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, epgb.build.ctx, "GroupBy")
	if err := epgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationPromptQuery, *EvaluationPromptGroupBy](ctx, epgb.build, epgb, epgb.build.inters, v)
}

func (epgb *EvaluationPromptGroupBy) sqlScan(ctx context.Context, root *EvaluationPromptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(epgb.fns))
	for _, fn := range epgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*epgb.flds)+len(epgb.fns))
		for _, f := range *epgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*epgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := epgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EvaluationPromptSelect is the builder for selecting fields of EvaluationPrompt entities.
type EvaluationPromptSelect struct {
	*EvaluationPromptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eps *EvaluationPromptSelect) Aggregate(fns ...AggregateFunc) *EvaluationPromptSelect {
	eps.fns = append(eps.fns, fns...)
	return eps
}

// Scan applies the selector query and scans the result into the given value.
func (eps *EvaluationPromptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eps.ctx, "Select")
	if err := eps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationPromptQuery, *EvaluationPromptSelect](ctx, eps.EvaluationPromptQuery, eps, eps.inters, v)
}

func (eps *EvaluationPromptSelect) sqlScan(ctx context.Context, root *EvaluationPromptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eps.fns))
	for _, fn := range eps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
