// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rherlt/reval/ent/request"
	"github.com/rherlt/reval/ent/response"
)

// RequestCreate is the builder for creating a Request entity.
type RequestCreate struct {
	config
	mutation *RequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExternalId sets the "externalId" field.
func (rc *RequestCreate) SetExternalId(s string) *RequestCreate {
	rc.mutation.SetExternalId(s)
	return rc
}

// SetNillableExternalId sets the "externalId" field if the given value is not nil.
func (rc *RequestCreate) SetNillableExternalId(s *string) *RequestCreate {
	if s != nil {
		rc.SetExternalId(*s)
	}
	return rc
}

// SetFrom sets the "from" field.
func (rc *RequestCreate) SetFrom(s string) *RequestCreate {
	rc.mutation.SetFrom(s)
	return rc
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (rc *RequestCreate) SetNillableFrom(s *string) *RequestCreate {
	if s != nil {
		rc.SetFrom(*s)
	}
	return rc
}

// SetSubject sets the "subject" field.
func (rc *RequestCreate) SetSubject(s string) *RequestCreate {
	rc.mutation.SetSubject(s)
	return rc
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (rc *RequestCreate) SetNillableSubject(s *string) *RequestCreate {
	if s != nil {
		rc.SetSubject(*s)
	}
	return rc
}

// SetBody sets the "body" field.
func (rc *RequestCreate) SetBody(s string) *RequestCreate {
	rc.mutation.SetBody(s)
	return rc
}

// SetDate sets the "date" field.
func (rc *RequestCreate) SetDate(t time.Time) *RequestCreate {
	rc.mutation.SetDate(t)
	return rc
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (rc *RequestCreate) SetNillableDate(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetDate(*t)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *RequestCreate) SetID(u uuid.UUID) *RequestCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RequestCreate) SetNillableID(u *uuid.UUID) *RequestCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (rc *RequestCreate) AddResponseIDs(ids ...uuid.UUID) *RequestCreate {
	rc.mutation.AddResponseIDs(ids...)
	return rc
}

// AddResponses adds the "responses" edges to the Response entity.
func (rc *RequestCreate) AddResponses(r ...*Response) *RequestCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rc.AddResponseIDs(ids...)
}

// Mutation returns the RequestMutation object of the builder.
func (rc *RequestCreate) Mutation() *RequestMutation {
	return rc.mutation
}

// Save creates the Request in the database.
func (rc *RequestCreate) Save(ctx context.Context) (*Request, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RequestCreate) SaveX(ctx context.Context) *Request {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RequestCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RequestCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RequestCreate) defaults() {
	if _, ok := rc.mutation.ID(); !ok {
		v := request.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RequestCreate) check() error {
	if _, ok := rc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Request.body"`)}
	}
	return nil
}

func (rc *RequestCreate) sqlSave(ctx context.Context) (*Request, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RequestCreate) createSpec() (*Request, *sqlgraph.CreateSpec) {
	var (
		_node = &Request{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(request.Table, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = rc.conflict
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.ExternalId(); ok {
		_spec.SetField(request.FieldExternalId, field.TypeString, value)
		_node.ExternalId = value
	}
	if value, ok := rc.mutation.From(); ok {
		_spec.SetField(request.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := rc.mutation.Subject(); ok {
		_spec.SetField(request.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := rc.mutation.Body(); ok {
		_spec.SetField(request.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := rc.mutation.Date(); ok {
		_spec.SetField(request.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if nodes := rc.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Request.Create().
//		SetExternalId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestUpsert) {
//			SetExternalId(v+v).
//		}).
//		Exec(ctx)
func (rc *RequestCreate) OnConflict(opts ...sql.ConflictOption) *RequestUpsertOne {
	rc.conflict = opts
	return &RequestUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rc *RequestCreate) OnConflictColumns(columns ...string) *RequestUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RequestUpsertOne{
		create: rc,
	}
}

type (
	// RequestUpsertOne is the builder for "upsert"-ing
	//  one Request node.
	RequestUpsertOne struct {
		create *RequestCreate
	}

	// RequestUpsert is the "OnConflict" setter.
	RequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetExternalId sets the "externalId" field.
func (u *RequestUpsert) SetExternalId(v string) *RequestUpsert {
	u.Set(request.FieldExternalId, v)
	return u
}

// UpdateExternalId sets the "externalId" field to the value that was provided on create.
func (u *RequestUpsert) UpdateExternalId() *RequestUpsert {
	u.SetExcluded(request.FieldExternalId)
	return u
}

// ClearExternalId clears the value of the "externalId" field.
func (u *RequestUpsert) ClearExternalId() *RequestUpsert {
	u.SetNull(request.FieldExternalId)
	return u
}

// SetFrom sets the "from" field.
func (u *RequestUpsert) SetFrom(v string) *RequestUpsert {
	u.Set(request.FieldFrom, v)
	return u
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *RequestUpsert) UpdateFrom() *RequestUpsert {
	u.SetExcluded(request.FieldFrom)
	return u
}

// ClearFrom clears the value of the "from" field.
func (u *RequestUpsert) ClearFrom() *RequestUpsert {
	u.SetNull(request.FieldFrom)
	return u
}

// SetSubject sets the "subject" field.
func (u *RequestUpsert) SetSubject(v string) *RequestUpsert {
	u.Set(request.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *RequestUpsert) UpdateSubject() *RequestUpsert {
	u.SetExcluded(request.FieldSubject)
	return u
}

// ClearSubject clears the value of the "subject" field.
func (u *RequestUpsert) ClearSubject() *RequestUpsert {
	u.SetNull(request.FieldSubject)
	return u
}

// SetBody sets the "body" field.
func (u *RequestUpsert) SetBody(v string) *RequestUpsert {
	u.Set(request.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *RequestUpsert) UpdateBody() *RequestUpsert {
	u.SetExcluded(request.FieldBody)
	return u
}

// SetDate sets the "date" field.
func (u *RequestUpsert) SetDate(v time.Time) *RequestUpsert {
	u.Set(request.FieldDate, v)
	return u
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RequestUpsert) UpdateDate() *RequestUpsert {
	u.SetExcluded(request.FieldDate)
	return u
}

// ClearDate clears the value of the "date" field.
func (u *RequestUpsert) ClearDate() *RequestUpsert {
	u.SetNull(request.FieldDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(request.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequestUpsertOne) UpdateNewValues() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(request.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Request.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestUpsertOne) Ignore() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestUpsertOne) DoNothing() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestCreate.OnConflict
// documentation for more info.
func (u *RequestUpsertOne) Update(set func(*RequestUpsert)) *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetExternalId sets the "externalId" field.
func (u *RequestUpsertOne) SetExternalId(v string) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetExternalId(v)
	})
}

// UpdateExternalId sets the "externalId" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateExternalId() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateExternalId()
	})
}

// ClearExternalId clears the value of the "externalId" field.
func (u *RequestUpsertOne) ClearExternalId() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearExternalId()
	})
}

// SetFrom sets the "from" field.
func (u *RequestUpsertOne) SetFrom(v string) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateFrom() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateFrom()
	})
}

// ClearFrom clears the value of the "from" field.
func (u *RequestUpsertOne) ClearFrom() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearFrom()
	})
}

// SetSubject sets the "subject" field.
func (u *RequestUpsertOne) SetSubject(v string) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateSubject() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateSubject()
	})
}

// ClearSubject clears the value of the "subject" field.
func (u *RequestUpsertOne) ClearSubject() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearSubject()
	})
}

// SetBody sets the "body" field.
func (u *RequestUpsertOne) SetBody(v string) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateBody() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateBody()
	})
}

// SetDate sets the "date" field.
func (u *RequestUpsertOne) SetDate(v time.Time) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateDate() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateDate()
	})
}

// ClearDate clears the value of the "date" field.
func (u *RequestUpsertOne) ClearDate() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearDate()
	})
}

// Exec executes the query.
func (u *RequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RequestUpsertOne.ID is not supported by MySQL driver. Use RequestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestCreateBulk is the builder for creating many Request entities in bulk.
type RequestCreateBulk struct {
	config
	builders []*RequestCreate
	conflict []sql.ConflictOption
}

// Save creates the Request entities in the database.
func (rcb *RequestCreateBulk) Save(ctx context.Context) ([]*Request, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Request, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RequestCreateBulk) SaveX(ctx context.Context) []*Request {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RequestCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RequestCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Request.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestUpsert) {
//			SetExternalId(v+v).
//		}).
//		Exec(ctx)
func (rcb *RequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestUpsertBulk {
	rcb.conflict = opts
	return &RequestUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rcb *RequestCreateBulk) OnConflictColumns(columns ...string) *RequestUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RequestUpsertBulk{
		create: rcb,
	}
}

// RequestUpsertBulk is the builder for "upsert"-ing
// a bulk of Request nodes.
type RequestUpsertBulk struct {
	create *RequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(request.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequestUpsertBulk) UpdateNewValues() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(request.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestUpsertBulk) Ignore() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestUpsertBulk) DoNothing() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestCreateBulk.OnConflict
// documentation for more info.
func (u *RequestUpsertBulk) Update(set func(*RequestUpsert)) *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetExternalId sets the "externalId" field.
func (u *RequestUpsertBulk) SetExternalId(v string) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetExternalId(v)
	})
}

// UpdateExternalId sets the "externalId" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateExternalId() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateExternalId()
	})
}

// ClearExternalId clears the value of the "externalId" field.
func (u *RequestUpsertBulk) ClearExternalId() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearExternalId()
	})
}

// SetFrom sets the "from" field.
func (u *RequestUpsertBulk) SetFrom(v string) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateFrom() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateFrom()
	})
}

// ClearFrom clears the value of the "from" field.
func (u *RequestUpsertBulk) ClearFrom() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearFrom()
	})
}

// SetSubject sets the "subject" field.
func (u *RequestUpsertBulk) SetSubject(v string) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateSubject() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateSubject()
	})
}

// ClearSubject clears the value of the "subject" field.
func (u *RequestUpsertBulk) ClearSubject() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearSubject()
	})
}

// SetBody sets the "body" field.
func (u *RequestUpsertBulk) SetBody(v string) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateBody() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateBody()
	})
}

// SetDate sets the "date" field.
func (u *RequestUpsertBulk) SetDate(v time.Time) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetDate(v)
	})
}

// UpdateDate sets the "date" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateDate() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateDate()
	})
}

// ClearDate clears the value of the "date" field.
func (u *RequestUpsertBulk) ClearDate() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearDate()
	})
}

// Exec executes the query.
func (u *RequestUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
