// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/rherlt/reval/ent/evaluation"
	"github.com/rherlt/reval/ent/predicate"
	"github.com/rherlt/reval/ent/request"
	"github.com/rherlt/reval/ent/response"
)

// ResponseQuery is the builder for querying Response entities.
type ResponseQuery struct {
	config
	ctx             *QueryContext
	order           []response.OrderOption
	inters          []Interceptor
	predicates      []predicate.Response
	withRequest     *RequestQuery
	withEvaluations *EvaluationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResponseQuery builder.
func (rq *ResponseQuery) Where(ps ...predicate.Response) *ResponseQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *ResponseQuery) Limit(limit int) *ResponseQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *ResponseQuery) Offset(offset int) *ResponseQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *ResponseQuery) Unique(unique bool) *ResponseQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *ResponseQuery) Order(o ...response.OrderOption) *ResponseQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryRequest chains the current query on the "request" edge.
func (rq *ResponseQuery) QueryRequest() *RequestQuery {
	query := (&RequestClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(response.Table, response.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, response.RequestTable, response.RequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvaluations chains the current query on the "evaluations" edge.
func (rq *ResponseQuery) QueryEvaluations() *EvaluationQuery {
	query := (&EvaluationClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(response.Table, response.FieldID, selector),
			sqlgraph.To(evaluation.Table, evaluation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, response.EvaluationsTable, response.EvaluationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Response entity from the query.
// Returns a *NotFoundError when no Response was found.
func (rq *ResponseQuery) First(ctx context.Context) (*Response, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{response.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *ResponseQuery) FirstX(ctx context.Context) *Response {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Response ID from the query.
// Returns a *NotFoundError when no Response ID was found.
func (rq *ResponseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{response.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *ResponseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Response entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Response entity is found.
// Returns a *NotFoundError when no Response entities are found.
func (rq *ResponseQuery) Only(ctx context.Context) (*Response, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{response.Label}
	default:
		return nil, &NotSingularError{response.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *ResponseQuery) OnlyX(ctx context.Context) *Response {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Response ID in the query.
// Returns a *NotSingularError when more than one Response ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *ResponseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{response.Label}
	default:
		err = &NotSingularError{response.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *ResponseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Responses.
func (rq *ResponseQuery) All(ctx context.Context) ([]*Response, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Response, *ResponseQuery]()
	return withInterceptors[[]*Response](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *ResponseQuery) AllX(ctx context.Context) []*Response {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Response IDs.
func (rq *ResponseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(response.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *ResponseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *ResponseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*ResponseQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *ResponseQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *ResponseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *ResponseQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResponseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *ResponseQuery) Clone() *ResponseQuery {
	if rq == nil {
		return nil
	}
	return &ResponseQuery{
		config:          rq.config,
		ctx:             rq.ctx.Clone(),
		order:           append([]response.OrderOption{}, rq.order...),
		inters:          append([]Interceptor{}, rq.inters...),
		predicates:      append([]predicate.Response{}, rq.predicates...),
		withRequest:     rq.withRequest.Clone(),
		withEvaluations: rq.withEvaluations.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithRequest tells the query-builder to eager-load the nodes that are connected to
// the "request" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResponseQuery) WithRequest(opts ...func(*RequestQuery)) *ResponseQuery {
	query := (&RequestClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRequest = query
	return rq
}

// WithEvaluations tells the query-builder to eager-load the nodes that are connected to
// the "evaluations" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResponseQuery) WithEvaluations(opts ...func(*EvaluationQuery)) *ResponseQuery {
	query := (&EvaluationClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withEvaluations = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ExternalId string `json:"externalId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Response.Query().
//		GroupBy(response.FieldExternalId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *ResponseQuery) GroupBy(field string, fields ...string) *ResponseGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResponseGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = response.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ExternalId string `json:"externalId,omitempty"`
//	}
//
//	client.Response.Query().
//		Select(response.FieldExternalId).
//		Scan(ctx, &v)
func (rq *ResponseQuery) Select(fields ...string) *ResponseSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &ResponseSelect{ResponseQuery: rq}
	sbuild.label = response.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResponseSelect configured with the given aggregations.
func (rq *ResponseQuery) Aggregate(fns ...AggregateFunc) *ResponseSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *ResponseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !response.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *ResponseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Response, error) {
	var (
		nodes       = []*Response{}
		_spec       = rq.querySpec()
		loadedTypes = [2]bool{
			rq.withRequest != nil,
			rq.withEvaluations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Response).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Response{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withRequest; query != nil {
		if err := rq.loadRequest(ctx, query, nodes, nil,
			func(n *Response, e *Request) { n.Edges.Request = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withEvaluations; query != nil {
		if err := rq.loadEvaluations(ctx, query, nodes,
			func(n *Response) { n.Edges.Evaluations = []*Evaluation{} },
			func(n *Response, e *Evaluation) { n.Edges.Evaluations = append(n.Edges.Evaluations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *ResponseQuery) loadRequest(ctx context.Context, query *RequestQuery, nodes []*Response, init func(*Response), assign func(*Response, *Request)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Response)
	for i := range nodes {
		fk := nodes[i].RequestId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "requestId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *ResponseQuery) loadEvaluations(ctx context.Context, query *EvaluationQuery, nodes []*Response, init func(*Response), assign func(*Response, *Evaluation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Response)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(evaluation.FieldResponseId)
	}
	query.Where(predicate.Evaluation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(response.EvaluationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResponseId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "responseId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *ResponseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *ResponseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(response.Table, response.Columns, sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, response.FieldID)
		for i := range fields {
			if fields[i] != response.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if rq.withRequest != nil {
			_spec.Node.AddColumnOnce(response.FieldRequestId)
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *ResponseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(response.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = response.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResponseGroupBy is the group-by builder for Response entities.
type ResponseGroupBy struct {
	selector
	build *ResponseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *ResponseGroupBy) Aggregate(fns ...AggregateFunc) *ResponseGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *ResponseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResponseQuery, *ResponseGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *ResponseGroupBy) sqlScan(ctx context.Context, root *ResponseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResponseSelect is the builder for selecting fields of Response entities.
type ResponseSelect struct {
	*ResponseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *ResponseSelect) Aggregate(fns ...AggregateFunc) *ResponseSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *ResponseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResponseQuery, *ResponseSelect](ctx, rs.ResponseQuery, rs, rs.inters, v)
}

func (rs *ResponseSelect) sqlScan(ctx context.Context, root *ResponseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
