/**
 * Evaluation API
 * This API is for evaluating responses from a response generator.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: mail@rherlt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScenarioStatistics } from './scenarioStatistics';


/**
 * The statistics of the evaluations grouped by scenario
 */
export interface GetStatisticsResponse { 
    scenarios?: Array<ScenarioStatistics>;
}

