/**
 * Evaluation API
 * This API is for evaluating responses from a response generator.
 *
 * The version of the OpenAPI document: 0.4
 * Contact: mail@rherlt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Message.
 */
export interface Message { 
    /**
     * Name of the author.
     */
    from: string;
    /**
     * e.g. E-Mail subject.
     */
    subject: string;
    /**
     * e.g. E-Mail body. The actual message.
     */
    body: string;
    /**
     * string containing the date when the email was received in ISO 8601 format.
     */
    date: string;
}

