/**
 * Evaluation API
 * This API is for evaluating responses from a response generator.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: mail@rherlt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The statistics of the evaluations
 */
export interface NameValuePair { 
    /**
     * Name of the category.
     */
    name: string;
    /**
     * Amout of rated question/response pairs in this category.
     */
    value: number;
}

