/**
 * Evaluation API
 * This API is for evaluating responses from a response generator.
 *
 * The version of the OpenAPI document: 0.3
 * Contact: mail@rherlt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The result of the current evaluation.
 */
export interface PostEvaluationRequest { 
    /**
     * Unique id of the evaluation.
     */
    id: string;
    evaluationResult: PostEvaluationRequest.EvaluationResultEnum;
}
export namespace PostEvaluationRequest {
    export type EvaluationResultEnum = 'neutral' | 'positive' | 'negative';
    export const EvaluationResultEnum = {
        Neutral: 'neutral' as EvaluationResultEnum,
        Positive: 'positive' as EvaluationResultEnum,
        Negative: 'negative' as EvaluationResultEnum
    };
}


