// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldExternalId holds the string denoting the externalid field in the database.
	FieldExternalId = "external_id"
	// EdgeEvaluations holds the string denoting the evaluations edge name in mutations.
	EdgeEvaluations = "evaluations"
	// Table holds the table name of the user in the database.
	Table = "users"
	// EvaluationsTable is the table that holds the evaluations relation/edge.
	EvaluationsTable = "evaluations"
	// EvaluationsInverseTable is the table name for the Evaluation entity.
	// It exists in this package in order to avoid circular dependency with the "evaluation" package.
	EvaluationsInverseTable = "evaluations"
	// EvaluationsColumn is the table column denoting the evaluations relation/edge.
	EvaluationsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldExternalId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByExternalId orders the results by the externalId field.
func ByExternalId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalId, opts...).ToFunc()
}

// ByEvaluationsCount orders the results by evaluations count.
func ByEvaluationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEvaluationsStep(), opts...)
	}
}

// ByEvaluations orders the results by evaluations terms.
func ByEvaluations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEvaluationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEvaluationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EvaluationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EvaluationsTable, EvaluationsColumn),
	)
}
