openapi: 3.0.3
info:
  title: Evaluation API
  description: This API is for evaluating responses from a response generator.
  contact:
    name: Rico Herlt
    email: mail@rherlt.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.3'
servers:
  - url: '{protocol}://{environment}:{port}/api/'
    variables:
      protocol:
        description: Protocol to use for the messages.
        default: http
        enum:
          - http
          - https
      environment:
        description: 'Environments: local (localhost)'
        default: localhost
        enum:
          - localhost
      port:
        description: Port to be used. Local ports are 8080 (http) and 8443 (https).
        default: '8080'
        enum:
          - '8080'
          - '443'
          - '80'
          - '8443'
tags:
  - name: Response Evaluation
    description: API for evaluating message responses.
  - name: Statistics
    description: API for evaluation statistics.
paths:
  /evaluation:
    get:
      tags:
        - Response Evaluation
      summary: Gets the next message for evaluation.
      description: Gets the next message for evaluation.
      operationId: GetEvaluation
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: Gets an evaluation response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEvaluationResponse'
        '404':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInformation'
    post:
      tags:
        - Response Evaluation
      summary: Posts the evaluation of the current evaluation response.
      description: Posts the next message evaluation.
      operationId: PostEvaluation
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody: 
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/PostEvaluationRequest'
      responses:
        '200':
          description: OK.
        '404':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInformation'
  /statistics:
    get:
      tags:
        - Statistics
      summary: Gets the statistics.
      description: Gets the statistics
      operationId: GetStatistics
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          description: Gets a scenario response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStatisticsResponse'
        '404':
          description: An error occured.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInformation'
components:
  parameters:
    Authorization:
      name: Authorization
      in: header
      description: JWT token with authorization information.
      required: false
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      schema:
        description: 'Bearer Token.'
        type: string
        pattern: (^(Bearer )?[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*$)
  schemas:
    ErrorInformation:
      type: object
      description: Information about the error.
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Some unique error code.
          example: 1001
        message:
          type: string
          description: Error message.
          example: Some very specific error ocured.
    PostEvaluationRequest:
      description: The result of the current evaluation.
      properties:
        id:
          type: string
          description: Unique id of the evaluation.
          example: 'fb336629-f0e5-4ce8-be96-3cf8de031b03'
        evaluationResult:
          type: string
          default: neutral
          enum:
            - neutral
            - positive
            - negative
      required: 
        - id
        - evaluationResult
    GetEvaluationResponse:
      description: The data of the next evaluation.
      properties:
        id:
          type: string
          description: Unique id of the evaluation.
          example: 'fb336629-f0e5-4ce8-be96-3cf8de031b03'
        response:
          $ref: '#/components/schemas/Message'
        request:
          $ref: '#/components/schemas/Message'
        evaluations:
          $ref: '#/components/schemas/Evaluations'
      required: 
        - id
        - response
        - request
        - evaluations
    Message:
      description: Message.
      properties:
        from:
          type: string
          description: Name of the author.
          example: Max Mustermann
        subject:
          type: string
          description: e.g. E-Mail subject.
          example: Important email 1.
        body:
          type: string
          description: e.g. E-Mail body. The actual message.
          example: Hi, this is my email.
        date:
          type: string
          description: string containing the date when the email was received in ISO 8601 format.
          example: 2012-04-23T18:25:43.511Z
      required: 
        - from
        - subject
        - body
        - date
    Evaluations:
      description: Evaluation statistics.
      properties:
        numNeutral:
          type: integer
          format: int32
          description: number of neutral evaluations.
        numPositive:
          type: integer
          format: int32
          description: Number of positive evaluations.
        numNegative:
          type: integer
          format: int32
          description: number of negative evaluations.
      required:
        - numNeutral
        - numPositive
        - numNegative
    ScenarioStatistics:
      description: Statistics per Scenario.
      properties:
        id:
          type: string
          description: Unique id of the evaluation.
          example: 'fb336629-f0e5-4ce8-be96-3cf8de031b03'
        name: 
          type: string
          description: The name of the Scenario
          example: 'Szenario 1'
        description:
          type: string
          description: The description of the Scenario.
          example: 'Das ist das erste tolle Szenario mit den Antworten aus Llama-2-13b-chat-hf_responses_rated_by_gpt-3.5-turbo.json'
        systemPrompt:
          type: string
          description: The used systemprompt for the scenario.
          example: '....'
        totalResponseCount:
          type: integer
          format: int32
          description: The amount of questions and response evaluated in this scenario.
          example: 400
        progressStatistics:
          type: array
          items:
            $ref: '#/components/schemas/NameValuePair'
        resultStatistics:
          type: array
          items:
            $ref: '#/components/schemas/NameValuePair'
        ratingScore:
          $ref: '#/components/schemas/RatingScore'
      required:
        - id
        - name
        - totalResponseCount
        - progressStatistics
        - resultStatistics
        - ratingScore
    GetStatisticsResponse:
      description: The statistics of the evaluations grouped by scenario
      properties:
        scenarios:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioStatistics'
    NameValuePair:
      description: The statistics of the evaluations
      properties:
        name:
          type: string
          description: Name of the category.
          example: 'positive'
        value:
          type: integer
          format: int32
          description: Amout of rated question/response pairs in this category.
          example: 12
      required:
        - name
        - value
    RatingScore:
      properties:
        min:
          type: number
          description: Minimum of rating Score.
          example: -1
        value:
          type: number
          description: Rating score of the scenario.
          example: 0.8
        max:
          type: number
          description: Maximum of rating Score.
          example: 1
      required:
      - min
      - value
      - max