// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Configuration is the predicate function for configuration builders.
type Configuration func(*sql.Selector)

// Evaluation is the predicate function for evaluation builders.
type Evaluation func(*sql.Selector)

// EvaluationPrompt is the predicate function for evaluationprompt builders.
type EvaluationPrompt func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// Response is the predicate function for response builders.
type Response func(*sql.Selector)

// Scenario is the predicate function for scenario builders.
type Scenario func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
