// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Evaluation is the predicate function for evaluation builders.
type Evaluation func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// Response is the predicate function for response builders.
type Response func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
